### ISSUE TITLE
Request to Modify the documentation

### ISSUE THREAD

**Issue by ponarunkumar** [googlecodelabs/cloud-cardboard-viewer#1]
The first step to "Enable YouTube API" should be updated from "...search for the “Google Cloud Trace API” to "..search for the “YouTube Data API v3”
![image](https://cloud.githubusercontent.com/assets/6130502/16999706/5bc21cb6-4e8d-11e6-8720-0e6645f05ff4.png)

**Comment by jmdobry** [comment]
Good catch.

**Comment by jmdobry** [comment]
Done

**Comment by ponarunkumar** [comment]
Thanks @jmdobry
