### ISSUE TITLE
Google Cloud Trace API not available

### ISSUE THREAD

**Issue by ponarunkumar** [googlecodelabs/cloud-cardboard-viewer#2]
As per the documentation, under API Manager >  Google APIs - the search to "Google Cloud Trace API" returned no result. However, Google Cloud APIs were available. It would be great if the documentation is updated with the up to date information or Google Cloud Trace API made available.

**Comment by jmdobry** [comment]
This codelab now been updated use "Stackdriver Trace API", which is the API's new name. The API is also automatically enabled for new projects.

**Comment by ponarunkumar** [comment]
Thanks
