### ISSUE TITLE
tar file has old app.yaml

### ISSUE THREAD

**Issue by mikelaramie** [googlecodelabs/cloud-cardboard-viewer#6]
When you try and deploy the app (Codelab step 7), it fails because the app.yaml file in the tar still has vm:true (instead of env:flex), and GCLOUD_PROJECT is not allowed anymore.

We should either update the tarball, or update the Codelab to pull directly from git?

**Comment by jmdobry** [comment]
The Codelab has been updated to pull the code directly from git, you no longer need the tarball.

https://codelabs.developers.google.com/codelabs/cloud-cardboard-viewer/index.html
