### ISSUE TITLE
Confusing API_KEY instructions on Step #5

### ISSUE THREAD

**Issue by Ernesto-Valdes** [googlecodelabs/cloud-cardboard-viewer#7]
<img width="844" alt="screen shot 2017-01-31 at 3 01 52 pm" src="https://cloud.githubusercontent.com/assets/4762763/22482762/674ebaec-e7c8-11e6-82e8-84f9afd00040.png">

The "replacing API_KEY with your project ID." is very confusing.

**Comment by jmdobry** [comment]
Sorry about that, it's been fixed now.
