### ISSUE TITLE
Problem importing already built angular 2 (npm start)

### ISSUE THREAD

**Issue by tranbenoit** [googlecodelabs/cloud-cardboard-viewer#9]
Hello !

It seems gcloud app deploy does a different npm start than Angular's quickstart (see https://github.com/angular/quickstart/blob/master/package.json)

**How to make an already made Angular 2 project to be deployable on GAE ?** 
The project in itself can be launched with the cloud shell command with "npm start" and be run locally (on google cloud's console). However, it seems the deployement isn't working.

I've added the app.yaml file and server.js . However, I think there might be some conflict with server.js's code since I have a bs-config.json file specifiying the server's launch.

**Comment by jmdobry** [comment]
The following steps will deploy that Angular quickstart to Google App Engine:

1.  Download the quickstart:

        git clone git@github.com:angular/quickstart.git

1.  Change into the `quickstart/` directory:

        cd quickstart

1.  Generate a custom `Dockerfile` (this will also generate the `app.yaml` file):

        gcloud beta app gen-config --custom

1.  Edit the generated `Dockerfile` and replace `CMD npm start` with:

        RUN npm install --only dev
        CMD npm run build && npm run serve:e2e

1.  Deploy:

        gcloud app deploy

You can see it deployed [here](https://quickstart-dot-nodejs-docs-samples.appspot.com/) (I'll leave that up for a few days).

**Comment by tranbenoit** [comment]
Thanks a lot ! It works !
I've completely forgotten about the use of Docker.
I've found an ugliest way also, still I prefer your way :
User the srever.js file to call the lite-server and make the application as an node-js launching a lite-server
```
var app = require('lite-server');

app.server({},function(){
	console.log('Server deployed on port: 8080');
	console.log('Press Ctrl+C to quit.');
});
```
And then edit package.json with the following :
```
"prestart": "npm install -g tsc && npm install concurrently -g && npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
```
Because it seems the deployment server doesn't know about the command tsc and concurrently.

Thanks for your help !
